//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tenis.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Torneo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Torneo()
        {
            this.EdicionTorneo = new HashSet<EdicionTorneo>();
        }
    
        public int IdTorneo { get; set; }
        [Required]
        [Display(Name = "Torneo")]
        public string Torneo1 { get; set; }
        [Required]
        [Display(Name = "Pais")]
        public Nullable<int> IdPais { get; set; }
        [Required]
        [Display(Name = "Tipo de torneo")]
        public Nullable<int> IdTipo { get; set; }
        [Required]
        [Display(Name = "Superficie")]
        public Nullable<int> IdSuperficie { get; set; }
        [Required]
        [Display(Name = "Estadio")]
        public Nullable<int> IdEstadio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EdicionTorneo> EdicionTorneo { get; set; }
        public virtual Estadio Estadio { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Superficie Superficie { get; set; }
        public virtual TipoTorneo TipoTorneo { get; set; }
    }
}
